add_hero_html
l-dmitry94/Battle-Frogs pull request #3
Opened 2023-08-23 19:52 UTC by orellesha9

2023-08-23 20:14 UTC, l-dmitry94 requested changes

2023-08-23 20:14 UTC, l-dmitry94 commented on src/partials/hero.html
> +    <button type="button" class="btn">Subscribe</button>
Об'єднай текст і кнопку в один div і дай йому клас

2023-08-24 19:23 UTC, orellesha9 commented on src/partials/hero.html
> +    <button type="button" class="btn">Subscribe</button>
Об'єднав

2023-08-24 20:20 UTC, l-dmitry94 approved these changes

2023-08-24 20:20 UTC, merged